"use client";

// dnd-kit identifies every draggable, droppable, and sortable target by an
// opaque string|number id. Sprint 7 partitioned the id space into three
// disjoint flavors so the `onDrag*` handlers can dispatch on intent
// without string-sniffing:
//
//   palette:${ComponentType}              — a card in the Add tab; drop creates a new node
//   node:${ComponentId}                   — a rendered canvas component; drop reorders/moves
//   dropzone:${ComponentId}               — an empty container's drop target; drop appends
//   between:${ComponentId}:${number}      — a sibling-gap drop target; drop inserts at the named index
//
// All constructors and parsers are pure and exported by name (no default
// exports). The parsers accept `unknown` because dnd-kit's
// `UniqueIdentifier` is `string | number`.

import type { ComponentId } from "@/lib/editor-state";
import { COMPONENT_TYPES, type ComponentType } from "@/lib/site-config";

const PALETTE_PREFIX = "palette:";
const NODE_PREFIX = "node:";
const DROPZONE_PREFIX = "dropzone:";
const BETWEEN_PREFIX = "between:";

export type PaletteDragId = `palette:${ComponentType}`;
export type NodeDragId = `node:${ComponentId}`;
export type DropZoneId = `dropzone:${ComponentId}`;
export type BetweenDropId = `between:${ComponentId}:${number}`;

export function paletteId(type: ComponentType): PaletteDragId {
  return `${PALETTE_PREFIX}${type}` as PaletteDragId;
}

export function nodeId(id: ComponentId): NodeDragId {
  return `${NODE_PREFIX}${id}` as NodeDragId;
}

export function dropZoneId(id: ComponentId): DropZoneId {
  return `${DROPZONE_PREFIX}${id}` as DropZoneId;
}

export function betweenId(parentId: ComponentId, index: number): BetweenDropId {
  return `${BETWEEN_PREFIX}${parentId}:${index}` as BetweenDropId;
}

const COMPONENT_TYPE_SET: ReadonlySet<string> = new Set(COMPONENT_TYPES);

function isComponentType(value: string): value is ComponentType {
  return COMPONENT_TYPE_SET.has(value);
}

export function isPaletteId(value: unknown): value is PaletteDragId {
  if (typeof value !== "string") return false;
  if (!value.startsWith(PALETTE_PREFIX)) return false;
  return isComponentType(value.slice(PALETTE_PREFIX.length));
}

export function isNodeId(value: unknown): value is NodeDragId {
  if (typeof value !== "string") return false;
  if (!value.startsWith(NODE_PREFIX)) return false;
  return value.length > NODE_PREFIX.length;
}

export function isDropZoneId(value: unknown): value is DropZoneId {
  if (typeof value !== "string") return false;
  if (!value.startsWith(DROPZONE_PREFIX)) return false;
  return value.length > DROPZONE_PREFIX.length;
}

export function isBetweenId(value: unknown): value is BetweenDropId {
  return parseBetweenId(value) !== null;
}

export function parsePaletteId(value: unknown): ComponentType | null {
  if (typeof value !== "string") return null;
  if (!value.startsWith(PALETTE_PREFIX)) return null;
  const tail = value.slice(PALETTE_PREFIX.length);
  return isComponentType(tail) ? tail : null;
}

export function parseNodeId(value: unknown): ComponentId | null {
  if (typeof value !== "string") return null;
  if (!value.startsWith(NODE_PREFIX)) return null;
  const tail = value.slice(NODE_PREFIX.length);
  return tail.length > 0 ? tail : null;
}

export function parseDropZoneId(value: unknown): ComponentId | null {
  if (typeof value !== "string") return null;
  if (!value.startsWith(DROPZONE_PREFIX)) return null;
  const tail = value.slice(DROPZONE_PREFIX.length);
  return tail.length > 0 ? tail : null;
}

// Between-zone ids encode `between:${parentId}:${index}`. Component ids are
// generated by `newComponentId` and never contain a colon, so the LAST
// colon in the tail is the index separator regardless of parentId shape.
export function parseBetweenId(value: unknown): { parentId: ComponentId; index: number } | null {
  if (typeof value !== "string") return null;
  if (!value.startsWith(BETWEEN_PREFIX)) return null;
  const tail = value.slice(BETWEEN_PREFIX.length);
  const lastColon = tail.lastIndexOf(":");
  if (lastColon <= 0) return null;
  const parentId = tail.slice(0, lastColon);
  const indexStr = tail.slice(lastColon + 1);
  if (!/^\d+$/.test(indexStr)) return null;
  const index = Number.parseInt(indexStr, 10);
  if (!Number.isFinite(index) || index < 0) return null;
  return { parentId, index };
}

const SIDE_PREFIX = "side:";
const SIDES = ["left", "right", "top", "bottom"] as const;
export type Side = (typeof SIDES)[number];
export type SideDropId = `side:${ComponentId}:${Side}`;

export function sideId(targetId: ComponentId, side: Side): SideDropId {
  return `${SIDE_PREFIX}${targetId}:${side}` as SideDropId;
}

export function isSideId(value: unknown): value is SideDropId {
  return parseSideId(value) !== null;
}

// Side ids encode `side:${targetId}:${side}`. Component ids never contain a
// colon (newComponentId rules), so the LAST colon in the tail is the side
// separator regardless of the targetId shape — same approach as parseBetweenId.
export function parseSideId(value: unknown): { targetId: ComponentId; side: Side } | null {
  if (typeof value !== "string") return null;
  if (!value.startsWith(SIDE_PREFIX)) return null;
  const tail = value.slice(SIDE_PREFIX.length);
  const lastColon = tail.lastIndexOf(":");
  if (lastColon <= 0) return null;
  const targetId = tail.slice(0, lastColon);
  const side = tail.slice(lastColon + 1);
  if (!(SIDES as readonly string[]).includes(side)) return null;
  return { targetId, side: side as Side };
}
