/**
 * Seed-uploads the demo stock-image library into the ai-stock-images bucket
 * and emits the seed SQL migration with the resolved public URLs.
 *
 * Usage:
 *   pnpm tsx scripts/seed-ai-stock-images.ts \
 *     --source "C:/Users/maxwa/OneDrive/Desktop/NebulaDemoPhotos/Property Images" \
 *     --out "supabase/migrations/<ts>_seed_ai_stock_images.sql"
 *
 * Reads SUPABASE_URL + SUPABASE_SERVICE_ROLE_KEY from .env.local.
 * Idempotent: re-running upserts files (overwrites bucket objects) and the
 * generated SQL uses ON CONFLICT (storage_path) DO NOTHING.
 */

import fs from "node:fs";
import path from "node:path";
import { createClient } from "@supabase/supabase-js";
import { config as loadEnv } from "dotenv";

loadEnv({ path: ".env.local" });

const BUCKET = "ai-stock-images";
const SKIP_EXTENSIONS = new Set([".htm", ".html"]);

type Args = { source: string; out: string };

function parseArgs(): Args {
  const args = process.argv.slice(2);
  const get = (k: string): string => {
    const i = args.indexOf(`--${k}`);
    if (i === -1 || !args[i + 1]) {
      throw new Error(`Missing --${k} <value>`);
    }
    return args[i + 1];
  };
  return { source: get("source"), out: get("out") };
}

type ImageEntry = {
  category: string;
  filename: string;
  storagePath: string;
  contentType: string;
};

function contentTypeFor(filename: string): string {
  const ext = path.extname(filename).toLowerCase();
  switch (ext) {
    case ".jpg":
    case ".jpeg":
      return "image/jpeg";
    case ".png":
      return "image/png";
    case ".webp":
      return "image/webp";
    case ".avif":
      return "image/avif";
    default:
      return "application/octet-stream";
  }
}

function walk(sourceDir: string): ImageEntry[] {
  const entries: ImageEntry[] = [];
  const subdirs = fs.readdirSync(sourceDir, { withFileTypes: true });
  for (const dirent of subdirs) {
    if (!dirent.isDirectory()) continue;
    const category = dirent.name;
    const folderPath = path.join(sourceDir, category);
    for (const file of fs.readdirSync(folderPath)) {
      const ext = path.extname(file).toLowerCase();
      if (SKIP_EXTENSIONS.has(ext)) {
        console.warn(`[skip] ${category}/${file} (extension not an image)`);
        continue;
      }
      entries.push({
        category,
        filename: file,
        storagePath: `default/${category}/${file}`,
        contentType: contentTypeFor(file),
      });
    }
  }
  return entries;
}

async function main(): Promise<void> {
  const { source, out } = parseArgs();
  const supabaseUrl = process.env.SUPABASE_URL ?? process.env.NEXT_PUBLIC_SUPABASE_URL;
  const serviceKey = process.env.SUPABASE_SERVICE_ROLE_KEY;
  if (!supabaseUrl || !serviceKey) {
    throw new Error("SUPABASE_URL + SUPABASE_SERVICE_ROLE_KEY required in .env.local");
  }
  const admin = createClient(supabaseUrl, serviceKey);

  const entries = walk(source);
  console.log(`Found ${entries.length} images under ${source}`);

  const rows: { storagePath: string; publicUrl: string; category: string }[] = [];

  for (const entry of entries) {
    const localPath = path.join(source, entry.category, entry.filename);
    const buffer = fs.readFileSync(localPath);
    const { error: uploadError } = await admin.storage
      .from(BUCKET)
      .upload(entry.storagePath, buffer, { contentType: entry.contentType, upsert: true });
    if (uploadError) {
      throw new Error(`Upload failed for ${entry.storagePath}: ${uploadError.message}`);
    }
    const { data } = admin.storage.from(BUCKET).getPublicUrl(entry.storagePath);
    if (!data?.publicUrl) {
      throw new Error(`No public URL for ${entry.storagePath}`);
    }
    rows.push({
      storagePath: entry.storagePath,
      publicUrl: data.publicUrl,
      category: entry.category,
    });
    console.log(`[ok] ${entry.storagePath}`);
  }

  const sqlLines: string[] = [
    "-- Generated by scripts/seed-ai-stock-images.ts.",
    "-- Re-run the script to regenerate after adding/removing source images.",
    "-- Descriptions are HAND-EDITED after generation; the script does not",
    "-- overwrite this file blindly — review before committing.",
    "",
    "insert into ai_stock_images (site_id, storage_path, public_url, category, description) values",
  ];
  const valueLines = rows.map((r, i) => {
    const sep = i === rows.length - 1 ? "" : ",";
    return `  (null, ${sqlString(r.storagePath)}, ${sqlString(r.publicUrl)}, ${sqlString(r.category)}, ${sqlString(`TODO: describe ${r.storagePath}`)})${sep}`;
  });
  sqlLines.push(...valueLines);
  sqlLines.push("on conflict (storage_path) do nothing;");
  sqlLines.push("");

  fs.writeFileSync(out, sqlLines.join("\n"), "utf8");
  console.log(`Wrote ${rows.length} rows to ${out}`);
}

function sqlString(value: string): string {
  return `'${value.replaceAll("'", "''")}'`;
}

void main().catch((e) => {
  console.error(e);
  process.exit(1);
});
